### ISSUE TITLE
error when using taper

### ISSUE THREAD

**Issue by Jakketet** [easyw/RF-tools-KiCAD#49]
Taper plugin gives error in OSX Monterey, have no clue what it means... also "rounding plugin" not working, did not have time to test rest of plugins

> 
> Traceback (most recent call last):
> 
> File "/Users/jt/Documents/KiCad/7.99/scripting/plugins/RF-tools-KiCAD-master/taper_fz/taper_plugin.py", line 33, in Run
> SetTaper_Zone(GetBoard())
> 
> File "/Users/jt/Documents/KiCad/7.99/scripting/plugins/RF-tools-KiCAD-master/taper_fz/taper.py", line 581, in SetTaper_Zone
> coor = __ComputePoints(track, pad, segs)
> 
> File "/Users/jt/Documents/KiCad/7.99/scripting/plugins/RF-tools-KiCAD-master/taper_fz/taper.py", line 246, in __ComputePoints
> np = start + VECTOR2I(wxPoint( vecT[0]*backoff, vecT[1]*backoff ))
> 
> File "/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pcbnew.py", line 5003, in __init__
> _pcbnew.VECTOR2I_swiginit(self, _pcbnew.new_VECTOR2I(*args))
> 
> TypeError: in method 'new_VECTOR2I', argument 1 of type 'VECTOR2< int > const &'
> Additional information:
> Wrong number or type of arguments for overloaded function 'new_VECTOR2I'.
> Possible C/C++ prototypes are:
> VECTOR2< int >::VECTOR2()
> VECTOR2< int >::VECTOR2(int,int)
> VECTOR2< int >::VECTOR2(VECTOR2< int > const &)

**Comment by easyw** [comment]
@Jakketet 
you are using kicad v7.99 
RF-tools are compatibile ATM w/ kv5, kv6, kv7
Not w/ kv7.99 wich is a nightly release.
